// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletTracker.Infrastructure.Persistence;

#nullable disable

namespace WalletTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WalletTrackerDbContext))]
    partial class WalletTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalletTracker.Domain.CostBasisLot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerTokenInQuote")
                        .HasColumnType("decimal(38,18)");

                    b.Property<decimal>("QuantityRemaining")
                        .HasColumnType("decimal(38,18)");

                    b.Property<long>("SourceTradeId")
                        .HasColumnType("bigint");

                    b.Property<long>("TokenPositionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenPositionId");

                    b.ToTable("CostBasisLots");
                });

            modelBuilder.Entity("WalletTracker.Domain.NewTokenAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Notified")
                        .HasColumnType("bit");

                    b.Property<string>("TokenAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TokenSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId", "TokenAddress")
                        .IsUnique();

                    b.ToTable("NewTokenAlerts");
                });

            modelBuilder.Entity("WalletTracker.Domain.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("WalletTracker.Domain.QuotePnL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("QuoteSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("RealizedPnL")
                        .HasColumnType("decimal(38,18)");

                    b.Property<decimal>("UnrealizedPnL")
                        .HasColumnType("decimal(38,18)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId", "QuoteSymbol")
                        .IsUnique();

                    b.ToTable("QuotePnLs");
                });

            modelBuilder.Entity("WalletTracker.Domain.TokenPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("LastKnownPriceInQuote")
                        .HasColumnType("decimal(38,18)");

                    b.Property<string>("QuoteSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("QuantityHeld")
                        .HasColumnType("decimal(38,18)");

                    b.Property<string>("TokenAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TokenSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId", "TokenAddress", "QuoteSymbol")
                        .IsUnique();

                    b.ToTable("TokenPositions");
                });

            modelBuilder.Entity("WalletTracker.Domain.TrackedWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("BackfillStatus")
                        .HasColumnType("int");

                    b.Property<int>("Chain")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCursor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Address", "Chain")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("WalletTracker.Domain.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountQuote")
                        .HasColumnType("decimal(38,18)");

                    b.Property<decimal>("AmountToken")
                        .HasColumnType("decimal(38,18)");

                    b.Property<DateTime>("BlockTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Chain")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DexName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerTokenInQuote")
                        .HasColumnType("decimal(38,18)");

                    b.Property<string>("QuoteSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TokenAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TokenSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId", "TokenAddress");

                    b.HasIndex("WalletId", "TxHash")
                        .IsUnique();

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("WalletTracker.Domain.WalletStats", b =>
                {
                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSells")
                        .HasColumnType("int");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("WinningSells")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.ToTable("WalletStats");
                });

            modelBuilder.Entity("WalletTracker.Domain.CostBasisLot", b =>
                {
                    b.HasOne("WalletTracker.Domain.TokenPosition", "TokenPosition")
                        .WithMany("Lots")
                        .HasForeignKey("TokenPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenPosition");
                });

            modelBuilder.Entity("WalletTracker.Domain.NewTokenAlert", b =>
                {
                    b.HasOne("WalletTracker.Domain.TrackedWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletTracker.Domain.QuotePnL", b =>
                {
                    b.HasOne("WalletTracker.Domain.TrackedWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletTracker.Domain.TokenPosition", b =>
                {
                    b.HasOne("WalletTracker.Domain.TrackedWallet", "Wallet")
                        .WithMany("Positions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletTracker.Domain.Trade", b =>
                {
                    b.HasOne("WalletTracker.Domain.TrackedWallet", "Wallet")
                        .WithMany("Trades")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletTracker.Domain.WalletStats", b =>
                {
                    b.HasOne("WalletTracker.Domain.TrackedWallet", "Wallet")
                        .WithOne("Stats")
                        .HasForeignKey("WalletTracker.Domain.WalletStats", "WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletTracker.Domain.TokenPosition", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("WalletTracker.Domain.TrackedWallet", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Stats");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
